/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_felyphenrique_Curses */

#ifndef _Included_com_github_felyphenrique_Curses
#define _Included_com_github_felyphenrique_Curses
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    raw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_felyphenrique_Curses_raw
  (JNIEnv *, jclass);

/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    cbreak
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_felyphenrique_Curses_cbreak
  (JNIEnv *, jclass);

/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    echo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_felyphenrique_Curses_echo
  (JNIEnv *, jclass);

/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    noecho
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_felyphenrique_Curses_noecho
  (JNIEnv *, jclass);

/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    keypad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_felyphenrique_Curses_keypad
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
