/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_felyphenrique_Curses */

#ifndef _Included_com_github_felyphenrique_Curses
#define _Included_com_github_felyphenrique_Curses
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_felyphenrique_Curses_start
  (JNIEnv *, jclass);

/*
 * Class:     com_github_felyphenrique_Curses
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_felyphenrique_Curses_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
